// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CreateCitizen', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CreateCitizen', async function() {
    await driver.get("https://municip.io:4200/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css(".border-2")).click()
    await driver.findElement(By.css(".rounded-\\[10px\\]:nth-child(1)")).click()
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("User")
    await driver.findElement(By.id("email")).sendKeys("userrrrrrrteste@teste.com")
    await driver.findElement(By.id("nif")).sendKeys("123456789")
    {
      const dropdown = await driver.findElement(By.id("gender"))
      await dropdown.findElement(By.xpath("//option[. = 'Masculino']")).click()
    }
    await driver.findElement(By.id("address")).click()
    await driver.findElement(By.id("address")).sendKeys("1")
    await driver.findElement(By.id("municipality")).click()
    {
      const dropdown = await driver.findElement(By.id("municipality"))
      await dropdown.findElement(By.xpath("//option[. = 'Almada']")).click()
    }
    await driver.findElement(By.id("surname")).click()
    await driver.findElement(By.id("surname")).sendKeys("Teste")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("1qaz\"WSX")
    await driver.findElement(By.id("birthDate")).click()
    await driver.findElement(By.id("birthDate")).sendKeys("0002-07-08")
    await driver.findElement(By.id("birthDate")).sendKeys("0020-07-08")
    await driver.findElement(By.id("birthDate")).sendKeys("0200-07-08")
    await driver.findElement(By.id("birthDate")).sendKeys("2002-07-08")
    await driver.findElement(By.id("postalCode1")).sendKeys("2870")
    await driver.findElement(By.id("postalCode2")).sendKeys("101")
    await driver.findElement(By.id("photo")).click()
    await driver.findElement(By.id("photo")).sendKeys("C:\\Users\\Utilizador\\Desktop\\4fE6Ncm.jpeg")
    await driver.findElement(By.css(".self-end")).click()
    await driver.findElement(By.css(".w-\\[13rem\\]")).click()
    await driver.findElement(By.css(".bg-black")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("userteste@teste.com")
    await driver.findElement(By.id("password")).sendKeys("1qaz\"WSX")
    await driver.findElement(By.css(".h-auto")).click()
  })
})
